package opcodes

// Define authentication handshake results
const (
	AUTH_HANDSHAKE_RESULT_OK        = 0x00
	AUTH_HANDSHAKE_RESULT_NOT_FOUND = 0x01
	AUTH_HANDSHAKE_RESULT_BANNED    = 0x02
	AUTH_HANDSHAKE_RESULT_ERR       = 0x03
)

// Define server opcodes (SMSG)
const (
	SMSG_OPCODE_AUTH_HANDSHAKE         uint16 = 0x02
	SMSG_OPCODE_PLAYER_ENTER_WORLD     uint16 = 0x100
	SMSG_OPCODE_PLAYER_UPDATE_POSITION uint16 = 0x101
	SMSG_OPCODE_PLAYER_UPDATE_ROTATION uint16 = 0x102
	SMSG_OPCODE_MESSAGECHAT            uint16 = 0x103
	SMSG_OPCODE_PLAYER_SYNC            uint16 = 0x105
	SMSG_OPCODE_PLAYER_DISCONNECT      uint16 = 0x108
	SMSG_OPCODE_SERVER_MESSAGE         uint16 = 0x110
	SMSG_OPCODE_MATCH_READY            uint16 = 0x200
)

// Define client opcodes (CMSG)
const (
	CMSG_OPCODE_AUTH_LOGIN             uint16 = 0x01
	CMSG_OPCODE_AUTH_REGISTER          uint16 = 0x02
	CMSG_OPCODE_MATCH_FIND_START       uint16 = 0x03
	CMSG_OPCODE_MATCH_FIND_CANCEL      uint16 = 0x04
	CMSG_OPCODE_PLAYER_ENTER_WORLD     uint16 = 0x05
	CMSG_OPCODE_PLAYER_UPDATE_POSITION uint16 = 0x06
	CMSG_OPCODE_PLAYER_UPDATE_ROTATION uint16 = 0x07
	CMSG_OPCODE_MESSAGECHAT            uint16 = 0x08
	CMSG_OPCODE_PLAYER_DISCONNECT      uint16 = 0x10
	CMSG_OPCODE_MATCH_WARM_UP          uint16 = 0x21
)
