package opcodes

// Define opcodes
const (

	// Server Opcodes
	SMSG_OPCODE_PLAYER_ENTER_WORLD     uint16 = 0x100
	SMSG_OPCODE_PLAYER_UPDATE_POSITION uint16 = 0x101
	SMSG_OPCODE_PLAYER_UPDATE_ROTATION uint16 = 0x102
	SMSG_MESSAGECHAT                   uint16 = 0x103
	SMSG_SERVER_MESSAGE                uint16 = 0x110
	SMSG_OPCODE_PLAYER_SYNC            uint16 = 0x105
	SMSG_OPCODE_PLAYER_DISCONNECT      uint16 = 0x108
)

const (
	// Client Opcodes
	CMSG_OPCODE_PLAYER_ENTER_WORLD     uint16 = 0x05
	CMSG_OPCODE_PLAYER_UPDATE_POSITION uint16 = 0x06
	CMSG_OPCODE_PLAYER_UPDATE_ROTATION uint16 = 0x07
	CMSG_OPCODE_MESSAGECHAT            uint16 = 0x08
	CMSG_OPCODE_PLAYER_DISCONNECT      uint16 = 0x10
)
